### ISSUE TITLE
Moped 2.0.7 undefined method `session'

### ISSUE THREAD

**Issue by whoteaches** [wilkerlucio/mongoid_taggable#36]
I'm having some issues related to mongoid_taggable and the way it queries on MOPED, which I have no idea how to fix.
mongoid_taggable tags query a MOPED collection (tags_index_collection), and when it queries the collection, I get undefined method `session'
I posted about it here:
http://stackoverflow.com/questions/35345003/moped-2-0-7-undefined-method-session

I have no idea what's going on here. I upgraded to MOPED 2.0.7 and I'm getting this undefined method `session'

```
User.tags_index_collection
 => #<Moped::Collection:0x007fa744fe2c50 @database=#<Mongo::Database:0x70178196887520 name=my_mongo_development>, @name="users_tags_index"> 
```

Then according to their documentation here, I should be able to do:

`User.tags_index_collection.find.entries`
But when I do, I get

```
NoMethodError: undefined method `session' for #<Mongo::Database:0x007fa744fe2fc0>
    from /Users/me/.rvm/gems/ruby-2.3.0/gems/moped-2.0.7/lib/moped/query.rb:501:in `session'
    from /Users/me/.rvm/gems/ruby-2.3.0/gems/moped-2.0.7/lib/moped/query.rb:93:in `cursor'
    from /Users/me/.rvm/gems/ruby-2.3.0/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
    from (irb):8:in `entries'
```

**Comment by whoteaches** [comment]
I finally had time to get back to this. No one maintains this repo, so I decided I'll add a solution here for anyone who's trying to get this tagging gem to work with Mongoid 5.

When you upgrade to mongoid 5+ you will also get rid of the deprecated Moped.
This mongoid_taggable gem is very short. It has very simple functionality, so just remove it from your gemfile, add it manually to your lib folder, require it in whatever class you need, then to make it work with mongoid 5, just replace Moped with the Mongo gem. See below:

```
def tags_index_collection
  @tags_index_collection ||= Mongo::Collection.new(self.collection.database, tags_index_collection_name)
end
```
